export const jobSet = [
  {
    group: 'Employments',
    title: 'JavaScript Developer',
    company: '8select Software GmbH, Regensburg',
    description:
      'JavaScript Software Developer specializing on Frontend Development. Design and Development of eCommerce Recommendation Widgets and corresponding Administration Panels, as well as integrating Shop Software Plugins, using ECMAScript 6, React / Redux, Angular, Node.js, REST, ElasticSearch, AWS infrastrucutre and more. ',
    from: new Date('05/01/2017'),
    to: new Date(Date.now()),
  },
  {
    group: 'Employments',
    title: 'Head of Frontend Development',
    company: 'ElectronicSales GmbH, Parsberg',
    description:
      'Front-end Development and UX Design Teamlead, Project and Team Coordination, Development of Cross-Device Responsive User Interfaces for B2B Webshops and Shop Admin Panels.',
    from: new Date('06/01/2014'),
    to: new Date('04/01/2017'),
  },
  {
    group: 'Employments',
    title: 'Frontend Developer',
    company: 'ElectronicSales GmbH, Parsberg',
    description:
      'Front-end Development for B2B and B2C eCommerce Projects, E-Mail Marketing Consultancy, Web Usability Consultancy, SEO Optimization, Creation of UX Design Concepts, Cross Device Responsive Web Design, HTML / CSS / JavaScript Solutions.  Product training and 3rd level technical support.',
    from: new Date('12/01/2011'),
    to: new Date('05/01/2014'),
  },
  {
    group: 'Employments',
    title: 'Media Designer',
    company: 'DTmedia GmbH, Denkendorf',
    description:
      'Creation of Design and Layout for Print and Web Media, strategic planning of Marketing Campaigns for Events and Small Business, Advertising Photography, Marketing Editorial, technical Training in Content Management Systems and Facebook Page Administration.',
    from: new Date('09/01/2009'),
    to: new Date('11/01/2011'),
  },
  {
    group: 'Training',
    title: 'Media Designer',
    company: 'DTmedia GmbH, Denkendorf',
    description: 'Creation of Design and Layout for Print and Web Media for Events and Small Business like Flyers, Logos, Business Cards, Posters, Banners, Magazines, etc.',
    from: new Date('09/01/2007'),
    to: new Date('08/01/2009'),
  },
  {
    group: 'Training',
    title: 'Car Painter',
    company: 'Auto Rudolf GmbH, Berching / Pollanten',
    description: 'Repair paint including car body paint reparing and filling, applying rust primer, performing paint jobs, paint mixing, cleaning of painting tools and facility equipment, etc.',
    from: new Date('09/01/2003'),
    to: new Date('05/20/2006'),
  },
  {
    group: 'Internships',
    title: 'Media Design',
    company: 'DTmedia GmbH, Denkendorf',
    description: 'Creation of print media including flyers, business cards, restaurant menus and web graphics.',
    from: new Date('10/01/2006'),
    to: new Date('07/31/2007'),
  },
  {
    group: 'Certificates',
    title: 'Certificate of Attendance: iJS 2017',
    company: 'iJS International JavaScript Conference',
    description: 'Web conference, October 23 - 27, 2017, Holiday Inn Munich City Centre. Topics covered: JavaScript / ECMA Script, Angular, React, Node.js, Web Development & Architecture, Agile & DevOps.',
    from: new Date('10/27/2017'),
  },
  {
    group: 'Certificates',
    title: 'Certificate of Attendance: Human Resources Management',
    company: 'Management College Eastern Bavaria, Regensburg',
    description: '16 hours training seminar title "From team member to supervisor - New in senior position", covering the topics of human resources management, team supervision, staff interviews, conflict conversations.',
    from: new Date('10/28/2015'),
  },
  {
    group: 'Certificates',
    title: 'Training Seminar: Usability',
    company: 'Macromedia University, Munich',
    description: 'Training seminar covering the topics of user behavior, target group analysis, basics of usbility and conversion rates, wording, e-branding and e-marketing, website optimization.',
    from: new Date('06/20/2011'),
  },
  {
    group: 'Certificates',
    title: 'Certifiacte of Examination: Digital and Print Media Designer',
    company: 'Chamber of Commerce and Industry Munich and Upper Bavaria',
    description: 'Examination Field: Design and Technology.',
    from: new Date('07/01/2009'),
  },
  {
    group: 'Certificates',
    title: 'KMK Foreign Languages Certificate: English',
    company: 'City of Munich, Capital of the Free State of Bavaria',
    description: 'KMK Grade II (European reference B2) - English.',
    from: new Date('05/17/2009'),
  },
  {
    group: 'Certificates',
    title: 'Certified Flash Developer',
    company: 'Macromedia University, Munich',
    description: '80 hours training seminar including Flash basics course, advanced Flash course, Flash ActionScripting course.',
    from: new Date('09/17/2009'),
  },
   {
    group: 'Certificates',
    title: 'Certifiacte of Examination: Car Painter',
    company: 'Chamber of Trade Munich and Upper Bavaria',
    from: new Date('05/20/2006'),
  },
]
